language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t romb1k/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true romb1k/react-test npm test

after_success:
  - docker build -t romb1k/multi-client ./client
  - docker build -t romb1k/multi-nginx ./nginx
  - docker build -t romb1k/multi-server ./server
  - docker build -t romb1k/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push romb1k/multi-client
  - docker push romb1k/multi-nginx
  - docker push romb1k/multi-server
  - docker push romb1k/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-675703781937
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY